sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
  - "6"
  - "7"
  - "node"

matrix:
  fast_finish: true

script:
  - npm run prod